require "omaussa.plugin_config.telescope"
require "omaussa.plugin_config.treesitter"
require "omaussa.plugin_config.lsp"
require "omaussa.plugin_config.cmp"
require "omaussa.plugin_config.copilot"
require "omaussa.plugin_config.neotree"
